#!/usr/bin/env node
/**
 * Scans public/assets/ and writes:
 *   - public/assets/catalog.json  (used by the asset browser: /assets.html)
 *   - docs/ASSET_LIST.md    (every model + its animation names, human/LLM readable)
 *
 *   npm run catalog
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { PACKS } from './fetch-assets.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ASSETS = path.join(ROOT, 'public', 'assets');

/** Read the JSON chunk of a .glb or a .gltf file. */
async function readGltfJson(file) {
  const buf = await fs.readFile(file);
  if (file.endsWith('.gltf')) return JSON.parse(buf.toString('utf8'));
  const len = buf.readUInt32LE(12); // first chunk = JSON
  return JSON.parse(buf.subarray(20, 20 + len).toString('utf8'));
}

async function walk(dir) {
  const out = [];
  for (const e of await fs.readdir(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) out.push(...(await walk(p)));
    else if (/\.(glb|gltf)$/i.test(e.name)) out.push(p);
  }
  return out;
}

const packs = [];
for (const meta of PACKS) {
  const dir = path.join(ASSETS, meta.id);
  try { await fs.access(dir); } catch { continue; }
  const models = [];
  for (const file of (await walk(dir)).sort()) {
    const json = await readGltfJson(file);
    const rel = path.relative(path.join(ROOT, 'public'), file).split(path.sep).join('/');
    models.push({
      name: path.basename(file).replace(/\.(glb|gltf)$/i, ''),
      url: '/' + rel,
      animated: !!json.skins?.length,
      animations: (json.animations ?? []).map((a) => a.name),
    });
  }
  packs.push({ id: meta.id, name: meta.name, license: meta.license, notes: meta.notes, models });
}

await fs.writeFile(path.join(ASSETS, 'catalog.json'), JSON.stringify(packs, null, 1));

let md = `# Asset list\n\n_Auto-generated by \`npm run catalog\` — don't edit by hand._\n\n` +
  `Load any of these with \`await assets.load('<url>')\` (see docs/ENGINE.md). ` +
  `Browse them visually at http://localhost:5173/assets.html\n\n`;
for (const p of packs) md += `- [${p.name}](#${p.id}) — ${p.models.length} models\n`;
for (const p of packs) {
  md += `\n## ${p.id}\n\n**${p.name}** · ${p.license}\n\n${p.notes}\n\n`;
  const statics = p.models.filter((m) => !m.animations.length);
  const anims = p.models.filter((m) => m.animations.length);
  for (const m of anims) {
    md += `- \`${m.url}\` — **${m.animations.length} animations**: ${m.animations.join(', ')}\n`;
  }
  if (statics.length) {
    const dir = statics[0].url.slice(0, statics[0].url.lastIndexOf('/') + 1);
    const sameDir = statics.every((m) => m.url.startsWith(dir) && !m.url.slice(dir.length).includes('/'));
    if (sameDir) {
      md += `\nStatic models in \`${dir}\`:\n\n${statics.map((m) => m.url.slice(dir.length)).join(', ')}\n`;
    } else {
      md += `\nStatic models:\n\n${statics.map((m) => m.url.replace(`/assets/${p.id}/`, '')).join(', ')}\n\n(prefix: \`/assets/${p.id}/\`)\n`;
    }
  }
}
await fs.writeFile(path.join(ROOT, 'docs', 'ASSET_LIST.md'), md);

const total = packs.reduce((s, p) => s + p.models.length, 0);
console.log(`Catalog: ${packs.length} packs, ${total} models -> public/assets/catalog.json, docs/ASSET_LIST.md`);
